export type Lang = 'en' | 'he';
export type Subject = 'math' | 'cs' | 'ai';
export type Stage = 'primary' | 'middle' | 'high';
export type Hobby = 'football' | 'gaming' | 'music' | 'space';
export type Profile = { lang: Lang; subject: Subject; stage: Stage; hobby: Hobby };
export type Bi = { en: string; he: string };
export const bi = (en: string, he: string): Bi => ({ en, he });
export const subjects = { math: bi('Mathematics', 'מתמטיקה'), cs: bi('Computer science', 'מדעי המחשב'), ai: bi('Learning with AI', 'ללמוד עם AI') };
export const stages = { primary: bi('Primary · Grades 4–6', 'יסודי · כיתות ד׳–ו׳'), middle: bi('Middle · Grades 7–9', 'חטיבה · כיתות ז׳–ט׳'), high: bi('High · Grades 10–12', 'תיכון · כיתות י׳–י״ב') };
export const hobbies = { football: bi('Football', 'כדורגל'), gaming: bi('Gaming', 'גיימינג'), music: bi('Music', 'מוזיקה'), space: bi('Space', 'חלל') };
export type Question = { id: string; title: Bi; prompt: Bi; expression: string; answer: number; variable?: string; hint: Bi; explanation: Bi; recovery: string; recoveryAnswer: number; source: Bi; level: number; kind: 'linear' | 'numeric' | 'quadratic' };
export function topic(p: Profile): Bi {
 if(p.subject === 'ai') return bi('Think first. Ask better.', 'חושבים קודם. שואלים טוב יותר.');
 if(p.subject === 'cs') return p.stage === 'primary' ? bi('Patterns & instructions', 'תבניות והוראות') : p.stage === 'middle' ? bi('Loops & variables', 'לולאות ומשתנים') : bi('Recursion, step by step', 'רקורסיה, צעד אחר צעד');
 return p.stage === 'primary' ? bi('Multiplication in the real world', 'כפל בעולם האמיתי') : p.stage === 'middle' ? bi('Making sense of equations', 'מבינים משוואות') : bi('Exploring quadratic equations', 'מגלים משוואות ריבועיות');
}
export function makeQuestion(p: Profile, level = 1, variant = 0): Question {
 const n = variant % 5; const h = hobbies[p.hobby];
 const q: Question = { id: `${p.subject}-${p.stage}-${level}-${variant}`, title: topic(p), prompt: bi('', ''), expression: '', answer: 0, hint: bi('', ''), explanation: bi('', ''), recovery: '', recoveryAnswer: 7, source: bi('Original demo exercise', 'תרגיל מקורי להדגמה'), level, kind: 'numeric' };
 if (p.subject === 'ai') {
  const a = 7+n, b = 7+level;
  return {...q, prompt: bi(`An AI says ${a} × ${b} = ${a*b-2}. Check the claim independently. What is the correct result?`, `כלי AI טוען ש־${a} × ${b} = ${a*b-2}. בדקו את הטענה בעצמכם. מה התוצאה הנכונה?`), expression: `${a} × ${b} = ?`, answer: a*b, hint: bi(`Break ${b} into two smaller numbers, multiply each by ${a}, and add.`, `פרקו את ${b} לשני מספרים קטנים, הכפילו כל אחד ב־${a} וחברו.`), explanation: bi('An AI can sound confident and still make a mistake. Use a calculation, a reliable source, or a second method to check its answer.', 'AI יכול להישמע בטוח ובכל זאת לטעות. בדקו את התשובה בעזרת חישוב, מקור אמין או דרך פתרון נוספת.'), recovery: '6 × 4 = ?', recoveryAnswer: 24};
 }
 if(p.subject === 'cs') {
  const limit = 3 + level + n;
  if(p.stage === 'primary') return {...q, prompt: bi(`A robot starts at square 0. It repeats “move ${level+1} squares” ${limit} times. Which square does it reach?`, `רובוט מתחיל במשבצת 0 וחוזר ${limit} פעמים על ״התקדם ${level+1} משבצות״. באיזו משבצת הוא יסיים?`), expression: `repeat ${limit} times:\n    move ${level+1}`, answer: limit*(level+1), hint: bi('Add the movement once for every repetition.', 'הוסיפו את מספר הצעדים בכל חזרה.'), explanation: bi('A loop repeats one instruction. Moving 2 squares three times means 2 + 2 + 2 = 6.', 'לולאה חוזרת על הוראה. תנועה של 2 משבצות שלוש פעמים היא 2 + 2 + 2 = 6.'), recovery: '2 + 2 + 2 = ?', recoveryAnswer: 6};
  if(p.stage === 'middle') return {...q, prompt: bi('Trace the loop. What number will this Python program print?', 'עקבו אחרי הלולאה. איזה מספר תוכנית ה־Python תדפיס?'), expression: `total = 0\nfor n in range(1, ${limit+1}):\n    total += n\nprint(total)`, answer: limit*(limit+1)/2, hint: bi(`range(1, ${limit+1}) includes 1 through ${limit}. Keep a running total.`, `range(1, ${limit+1}) כולל את המספרים מ־1 עד ${limit}. עקבו אחר הסכום המצטבר.`), explanation: bi('The upper end of range is excluded. In range(1, 4), n is 1, then 2, then 3. The total becomes 1, 3, then 6.', 'הגבול העליון של range אינו כלול. ב־range(1, 4), הערך של n הוא 1, אחר כך 2 ואז 3. הסכום הוא 1, 3 ואז 6.'), recovery: '1 + 2 + 3 = ?', recoveryAnswer: 6};
  return {...q, prompt: bi('Follow the recursive calls down to the base case. What does this code print?', 'עקבו אחרי הקריאות הרקורסיביות עד לתנאי העצירה. מה הקוד מדפיס?'), expression: `def count(n):\n    if n == 0:\n        return 0\n    return n + count(n - 1)\n\nprint(count(${limit}))`, answer: limit*(limit+1)/2, hint: bi(`Expand count(${limit}) into ${limit} + count(${limit-1}). Stop at count(0).`, `פרקו את count(${limit}) ל־${limit} + count(${limit-1}). עצרו ב־count(0).`), explanation: bi('Recursion solves a smaller version of the same problem until a base case. count(2) = 2 + count(1) = 2 + 1 + count(0) = 3.', 'רקורסיה פותרת גרסה קטנה יותר של אותה בעיה עד לתנאי עצירה. count(2) = 2 + count(1) = 2 + 1 + count(0) = 3.'), recovery: 'count(2) = ?', recoveryAnswer: 3};
 }
 if(p.stage === 'primary') {
  const a = 3+level, b = 4+n, remove = level>1 ? level+2 : 0;
  return {...q, prompt: bi(`Your ${h.en.toLowerCase()} club has ${a} packs with ${b} stickers each.${remove ? ` You give away ${remove} stickers.` : ''} How many stickers ${remove ? 'remain' : 'are there'}?`, `במועדון ה${h.he} שלכם יש ${a} חבילות, בכל אחת ${b} מדבקות.${remove ? ` נתתם ${remove} מדבקות לחבר.` : ''} כמה מדבקות ${remove ? 'נשארו' : 'יש בסך הכול'}?`), expression: `${a} × ${b}${remove ? ` − ${remove}` : ''} = ?`, answer: a*b-remove, hint: bi('First count all equal groups using multiplication. Then subtract anything given away.', 'ספרו קודם את כל הקבוצות השוות בעזרת כפל. אחר כך הפחיתו את מה שנתתם.'), explanation: bi('Multiplication counts equal groups. Three packs with four stickers each means 4 + 4 + 4 = 12 stickers.', 'כפל סופר קבוצות שוות. שלוש חבילות עם ארבע מדבקות בכל אחת הן 4 + 4 + 4 = 12 מדבקות.'), recovery: '3 × 4 = ?', recoveryAnswer: 12};
 }
 if(p.stage === 'high') {
  const root = 3+n, coefficient = level;
  return {...q, kind: 'quadratic', variable: 'x', prompt: bi('Find the positive solution of this quadratic equation. You may submit your working one step at a time.', 'מצאו את הפתרון החיובי של המשוואה הריבועית. אפשר לשלוח את דרך הפתרון צעד אחר צעד.'), expression: `${coefficient>1 ? coefficient : ''}x² − ${coefficient*root*root} = 0`, answer: root, hint: bi('Isolate x² first. A positive square root is the positive number whose square gives that value.', 'בודדו קודם את x². השורש החיובי הוא המספר החיובי שהריבוע שלו נותן את הערך הזה.'), explanation: bi('If x² = 16, then x = 4 or x = −4. When a question asks for the positive solution, choose 4.', 'אם x² = 16, אז x = 4 או x = −4. כשמבקשים את הפתרון החיובי, בוחרים 4.'), recovery: 'y² = 25; y > 0. y = ?', recoveryAnswer: 5};
 }
 const a = 2+level, x = 5+n, b = 4+2*level;
 return {...q, variable: 'x', kind: 'linear', prompt: bi(`You’re organizing a ${h.en.toLowerCase()} meetup. ${a} equal packs and ${b} extra stickers give you ${a*x+b} stickers in total. How many stickers are in each pack?`, `אתם מארגנים מפגש ${h.he}. ב־${a} חבילות זהות ועוד ${b} מדבקות בודדות יש יחד ${a*x+b} מדבקות. כמה מדבקות יש בכל חבילה?`), expression: `${a}x + ${b} = ${a*x+b}`, answer: x, hint: bi(`What operation cancels +${b}? Apply it to both sides before dividing.`, `איזו פעולה מבטלת את ${b}+? בצעו אותה בשני האגפים לפני החלוקה.`), explanation: bi('An equation is a balance. Doing the same operation to both sides keeps it equal. For 2y + 4 = 18, subtract 4 from both sides to get 2y = 14, then divide both sides by 2.', 'משוואה היא כמו מאזניים. אותה פעולה בשני האגפים שומרת על השוויון. ב־2y + 4 = 18 מחסרים 4 משני האגפים ומקבלים 2y = 14, ואז מחלקים את שני האגפים ב־2.'), recovery: 'y + 4 = 11. y = ?', recoveryAnswer: 7};
}
export function story(p: Profile): { title: Bi; paragraphs: Bi[]; takeaway: Bi; source: Bi } {
 const h = hobbies[p.hobby];
 let paragraphs: Bi[]; let takeaway: Bi;
 if(p.subject === 'math' && p.stage === 'middle') {
  paragraphs = [bi(`Imagine planning a ${h.en.toLowerCase()} meetup with your friends. You have three identical mystery packs of stickers, plus six loose stickers. Altogether, you count 21.`, `דמיינו שאתם מתכננים מפגש ${h.he} עם חברים. יש לכם שלוש חבילות מסתוריות וזהות של מדבקות ועוד שש מדבקות בודדות. בסך הכול ספרתם 21.`), bi('How many stickers are hiding in each pack? Call that unknown number x. Your story becomes an equation: 3x + 6 = 21.', 'כמה מדבקות מסתתרות בכל חבילה? נקרא למספר הלא ידוע x. הסיפור שלכם הופך למשוואה: 3x + 6 = 21.'), bi('Set the six loose stickers aside: 15 remain in the packs. Share them equally across three packs and you discover five in each. You just solved for x.', 'מניחים בצד את שש המדבקות הבודדות: נשארו 15 בחבילות. מחלקים אותן שווה בשווה בין שלוש חבילות ומגלים חמש בכל חבילה. הרגע מצאתם את x.')];
  takeaway = bi('Keep both sides balanced. Undo addition first, then multiplication.', 'שומרים על איזון בשני האגפים. מבטלים קודם את החיבור, ואז את הכפל.');
 } else if(p.subject === 'math' && p.stage === 'primary') {
  paragraphs = [bi(`Your ${h.en.toLowerCase()} club makes four sticker packs. Each pack has four stickers. You could count every sticker, but equal groups give you a shortcut.`, `במועדון ה${h.he} שלכם מכינים ארבע חבילות מדבקות. בכל חבילה ארבע מדבקות. אפשר לספור מדבקה אחרי מדבקה, אבל קבוצות שוות נותנות קיצור דרך.`), bi('Four groups of four is 4 + 4 + 4 + 4. Multiplication writes the same idea as 4 × 4 = 16.', 'ארבע קבוצות של ארבע הן 4 + 4 + 4 + 4. כפל כותב את אותו הרעיון בתור 4 × 4 = 16.'), bi('If you share three stickers with a friend, subtract them after counting the whole collection: 16 − 3 = 13.', 'אם נותנים שלוש מדבקות לחבר, מפחיתים אותן אחרי שסופרים את כל האוסף: 16 − 3 = 13.')]; takeaway = bi('Multiply equal groups. Subtract what you give away.', 'כופלים קבוצות שוות. מפחיתים את מה שנותנים.');
 } else if(p.subject === 'math') {
  paragraphs = [bi(`You’re designing a square display for your ${h.en.toLowerCase()} club. It needs an area of 16 square metres. How long should each side be?`, `אתם מעצבים מתחם ריבועי למועדון ה${h.he} שלכם. השטח צריך להיות 16 מטרים רבועים. מה יהיה האורך של כל צלע?`), bi('Area is side × side, so x² = 16. Both 4² and (−4)² equal 16, but a physical length must be positive.', 'שטח ריבוע הוא צלע כפול צלע, לכן x² = 16. גם 4² וגם (−4)² שווים 16, אבל אורך פיזי חייב להיות חיובי.'), bi('Each side is 4 metres. The context helped us choose the positive solution from two mathematical possibilities.', 'האורך של כל צלע הוא 4 מטרים. ההקשר עזר לנו לבחור את הפתרון החיובי מתוך שתי אפשרויות מתמטיות.')]; takeaway = bi('A square equation may have two solutions. Check which ones fit the question.', 'למשוואה ריבועית יכולים להיות שני פתרונות. בודקים אילו מהם מתאימים לשאלה.');
 } else if(p.subject === 'cs') {
  paragraphs = p.stage === 'high' ? [bi(`Your ${h.en.toLowerCase()} club tracks a challenge: earn 1 point on day one, 2 on day two, and so on. How can code calculate the total?`, `מועדון ה${h.he} שלכם עוקב אחרי אתגר: נקודה ביום הראשון, שתי נקודות ביום השני, וכן הלאה. איך קוד יכול לחשב את הסכום?`), bi('Define count(n) as n + count(n − 1). Each call handles one day and asks a smaller version of the same question.', 'נגדיר count(n) בתור n + count(n − 1). כל קריאה מטפלת ביום אחד ושואלת גרסה קטנה יותר של אותה שאלה.'), bi('The base case count(0) = 0 stops the calls. For three days: 3 + 2 + 1 + 0 = 6.', 'תנאי העצירה count(0) = 0 עוצר את הקריאות. עבור שלושה ימים: 3 + 2 + 1 + 0 = 6.')] : [bi(`Imagine a robot helping at your ${h.en.toLowerCase()} club. Instead of giving the same instruction again and again, you teach it to repeat.`, `דמיינו רובוט שעוזר במועדון ה${h.he} שלכם. במקום לתת את אותה הוראה שוב ושוב, מלמדים אותו לחזור עליה.`), bi('A loop runs an instruction a chosen number of times. A variable remembers a value that can change during each repetition.', 'לולאה מפעילה הוראה מספר מסוים של פעמים. משתנה זוכר ערך שיכול להשתנות בכל חזרה.'), bi('Track each repetition on paper. If you add 1, then 2, then 3 to a total that starts at zero, the final total is 6.', 'עקבו על הנייר אחרי כל חזרה. אם מוסיפים 1, אחר כך 2 ואז 3 לסכום שמתחיל באפס, הסכום הסופי הוא 6.')]; takeaway = p.stage === 'high' ? bi('Find the base case, then trace the calls back up.', 'מוצאים את תנאי העצירה, ואז עוקבים חזרה אחרי הקריאות.') : bi('Trace one repetition at a time. Watch what changes.', 'עוקבים אחרי חזרה אחת בכל פעם ובודקים מה משתנה.');
 } else {
  paragraphs = [bi(`You ask AI to help plan a ${h.en.toLowerCase()} challenge. It gives you a confident answer. Does confidence mean it is correct?`, `ביקשתם מ־AI עזרה בתכנון אתגר ${h.he}. הוא נתן תשובה בטוחה. האם ביטחון אומר שהתשובה נכונה?`), bi('Start with your own attempt. Ask for one hint, then explain the next step in your own words. This makes AI a learning partner.', 'מתחילים בניסיון עצמאי. מבקשים רמז אחד, ואז מסבירים את הצעד הבא במילים שלכם. כך AI הופך לשותף ללמידה.'), bi('Check factual claims against a trusted source and calculations with another method. Never include your address, school, passwords, or identifying details in a prompt.', 'בודקים טענות בעזרת מקור אמין וחישובים בדרך נוספת. לא מכניסים לשאלה כתובת, שם בית הספר, סיסמאות או פרטים מזהים.')]; takeaway = bi('Try → ask for a hint → verify → explain it yourself.', 'מנסים ← מבקשים רמז ← בודקים ← מסבירים בעצמנו.');
 }
 return {title: bi(`A little ${h.en.toLowerCase()}. A new way to understand.`, `קצת ${h.he}. דרך חדשה להבין.`), paragraphs, takeaway, source: bi('Curated demo lesson · not an official curriculum source', 'שיעור הדגמה מקורי · אינו מקור רשמי של תוכנית הלימודים')};
}
