'use client';
import { FormEvent,useState } from 'react';
import { ArrowRight,CheckCircle2,Smartphone,Mail } from 'lucide-react';
import { AccountProfile,profileSchema,otpSchema } from '@/lib/auth-validation';
import { AuthFrame,AuthLang,useAuthLanguage,authErrorText,useCooldown } from './shared';
export default function Onboarding({email,initialProfile,initialLang,emailVerified}:{email:string;initialProfile:Partial<AccountProfile>;initialLang:AuthLang;emailVerified:boolean}){
 const {lang,setLang,t}=useAuthLanguage(initialLang);const [details,setDetails]=useState({first_name:initialProfile.first_name||'',last_name:initialProfile.last_name||'',city:initialProfile.city||'',age:initialProfile.age?.toString()||'',phone:initialProfile.phone||''});
 const [step,setStep]=useState<'details'|'sms'>('details');const [phone,setPhone]=useState('');const [token,setToken]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const {remaining,start}=useCooldown();
 async function request(path:string,body:unknown){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'unavailable');return data;}
 async function save(event:FormEvent){event.preventDefault();if(busy)return;setError('');const parsed=profileSchema.safeParse({...details,locale:lang});if(!parsed.success){setError('invalid_profile');return;}setBusy(true);
  try{const data=await request('/api/account/profile',parsed.data);if(data.complete){window.location.assign('/account');return;}
   const sent=await request('/api/account/phone',{action:'send'});if(sent.complete){window.location.assign('/account');return;}setPhone(parsed.data.phone);setStep('sms');setToken('');start();
  }catch(e){setError(e instanceof Error?e.message:'unavailable');}finally{setBusy(false);}
 }
 async function verify(event:FormEvent){event.preventDefault();if(busy)return;const parsed=otpSchema.safeParse(token);if(!parsed.success){setError('invalid_code');return;}setBusy(true);setError('');
  try{const data=await request('/api/account/phone',{action:'verify',token:parsed.data});if(data.complete)window.location.assign('/account');else setError('verification_incomplete');}catch(e){setError(e instanceof Error?e.message:'unavailable');}finally{setBusy(false);}
 }
 async function resend(){if(busy||remaining)return;setBusy(true);setError('');try{const data=await request('/api/account/phone',{action:'resend'});if(data.complete){window.location.assign('/account');return;}start();}catch(e){setError(e instanceof Error?e.message:'unavailable');}finally{setBusy(false);}}
 const input=(field:keyof typeof details,label:string,extra:Record<string,unknown>={})=><label className="auth-field">{label}<input value={details[field]} onChange={e=>setDetails({...details,[field]:e.target.value})} required maxLength={field==='city'?100:60} {...extra}/></label>;
 return <AuthFrame lang={lang} onLanguage={()=>setLang(lang==='he'?'en':'he')} step={step==='sms'?2:1}>
  <div className="auth-card-label">{t('ONE ACCOUNT. ALL YOUR LEARNING.','חשבון אחד. כל הלמידה שלכם.')}</div><h1>{step==='sms'?t('One last little check','עוד בדיקה קטנה'):t('Make yourself at home','עכשיו זה המקום שלכם')}</h1><p className="auth-subtitle">{step==='sms'?t('Enter the code sent to your phone.','הזינו את הקוד שנשלח לטלפון שלכם.'):t('Complete your details, then verify your mobile number.','משלימים את הפרטים ואז מאמתים את הטלפון הנייד.')}</p>
  <div className={`auth-verified ${emailVerified?'':'unverified'}`}><Mail size={18}/><bdi dir="ltr">{email}</bdi>{emailVerified?<><CheckCircle2 size={17}/><span>{t('Verified','מאומת')}</span></>:<span>{t('Needs verification','דורש אימות')}</span>}</div>
  {!emailVerified&&<div className="auth-error">{authErrorText('email_required',lang)}</div>}{error&&<div className="auth-error" role="alert">{authErrorText(error,lang)}</div>}
  {step==='details'?<form onSubmit={save} className="auth-form"><div className="auth-field-row">{input('first_name',t('First name','שם פרטי'),{autoComplete:'given-name'})}{input('last_name',t('Last name','שם משפחה'),{autoComplete:'family-name'})}</div><div className="auth-field-row city-age">{input('city',t('City / town','עיר / יישוב'),{autoComplete:'address-level2'})}{input('age',t('Age','גיל'),{type:'number',min:1,max:120,maxLength:undefined})}</div>{input('phone',t('Mobile number','טלפון נייד'),{type:'tel',dir:'ltr',autoComplete:'tel',placeholder:'050-123-4567',maxLength:24})}<p className="auth-field-note">{t('A city or town is enough. We don’t ask for your street address.','מספיק שם עיר או יישוב. אין צורך בכתובת מדויקת.')}</p><button className="primary-button auth-submit" disabled={busy||!emailVerified}>{busy?t('Getting ready…','מכינים הכול…'):t('Save details & verify phone','שמירת הפרטים ואימות הטלפון')}<ArrowRight size={17}/></button></form>:<>
   <div className="auth-recipient"><Smartphone size={21}/><bdi dir="ltr">{phone}</bdi></div><form onSubmit={verify} className="auth-form"><label className="auth-field">{t('SMS verification code','קוד האימות ב־SMS')}<input className="otp-input" autoFocus autoComplete="one-time-code" inputMode="numeric" dir="ltr" value={token} onChange={e=>setToken(e.target.value.replace(/\D/g,''))} pattern="[0-9]{6,10}" maxLength={10} required/></label><button className="primary-button auth-submit" disabled={busy}>{busy?t('Verifying…','מאמתים…'):t('Verify phone & finish','אימות הטלפון וסיום')}<ArrowRight size={17}/></button></form>
   <div className="auth-resend"><span>{t('Didn’t receive a text?','ההודעה לא הגיעה?')}</span><button disabled={remaining>0||busy} onClick={resend}>{remaining?t(`Resend in ${remaining}s`,`שליחה חוזרת בעוד ${remaining} שניות`):t('Send a new code','שליחת קוד חדש')}</button></div><button className="auth-back" onClick={()=>{setStep('details');setToken('');setError('');}}>{t('Change phone number','שינוי מספר הטלפון')}</button>
  </>}
 </AuthFrame>;
}
